"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
option csharp_namespace = "Starward.RPC.GameInstall";"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SophonChunkManifest(_message.Message):
    """Chunk 模式游戏文件清单"""

    DESCRIPTOR: _descriptor.Descriptor

    CHUNCKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def chuncks(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonChunkFile]: ...
    def __init__(
        self,
        *,
        chuncks: _abc.Iterable[Global___SophonChunkFile] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chuncks", b"chuncks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonChunkManifest: _TypeAlias = SophonChunkManifest  # noqa: Y015

@_typing.final
class SophonChunkFile(_message.Message):
    """Chunk 模式游戏文件"""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    CHUNKS_FIELD_NUMBER: _builtins.int
    IS_FOLDER_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    is_folder: _builtins.bool
    size: _builtins.int
    md5: _builtins.str
    @_builtins.property
    def chunks(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonChunk]: ...
    def __init__(
        self,
        *,
        file: _builtins.str = ...,
        chunks: _abc.Iterable[Global___SophonChunk] | None = ...,
        is_folder: _builtins.bool = ...,
        size: _builtins.int = ...,
        md5: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunks", b"chunks", "file", b"file", "is_folder", b"is_folder", "md5", b"md5", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonChunkFile: _TypeAlias = SophonChunkFile  # noqa: Y015

@_typing.final
class SophonChunk(_message.Message):
    """Chunk 模式游戏文件块"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    UNCOMPRESSED_MD5_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    COMPRESSED_SIZE_FIELD_NUMBER: _builtins.int
    UNCOMPRESSED_SIZE_FIELD_NUMBER: _builtins.int
    UNKNOWN_FIELD_NUMBER: _builtins.int
    COMPRESSED_MD5_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    uncompressed_md5: _builtins.str
    offset: _builtins.int
    compressed_size: _builtins.int
    uncompressed_size: _builtins.int
    unknown: _builtins.int
    compressed_md5: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        uncompressed_md5: _builtins.str = ...,
        offset: _builtins.int = ...,
        compressed_size: _builtins.int = ...,
        uncompressed_size: _builtins.int = ...,
        unknown: _builtins.int = ...,
        compressed_md5: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compressed_md5", b"compressed_md5", "compressed_size", b"compressed_size", "id", b"id", "offset", b"offset", "uncompressed_md5", b"uncompressed_md5", "uncompressed_size", b"uncompressed_size", "unknown", b"unknown"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonChunk: _TypeAlias = SophonChunk  # noqa: Y015

@_typing.final
class SophonPatchManifest(_message.Message):
    """Patch 更新模式游戏文件清单"""

    DESCRIPTOR: _descriptor.Descriptor

    PATCHES_FIELD_NUMBER: _builtins.int
    DELETE_TAGS_FIELD_NUMBER: _builtins.int
    COMPRESS_MODE_FIELD_NUMBER: _builtins.int
    compress_mode: _builtins.int
    """压缩模式"""
    @_builtins.property
    def patches(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonPatchFile]:
        """新版本所有文件"""

    @_builtins.property
    def delete_tags(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonPatchDeleteTag]:
        """需要删除的文件"""

    def __init__(
        self,
        *,
        patches: _abc.Iterable[Global___SophonPatchFile] | None = ...,
        delete_tags: _abc.Iterable[Global___SophonPatchDeleteTag] | None = ...,
        compress_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compress_mode", b"compress_mode", "delete_tags", b"delete_tags", "patches", b"patches"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchManifest: _TypeAlias = SophonPatchManifest  # noqa: Y015

@_typing.final
class SophonPatchFile(_message.Message):
    """Patch 更新模式，新版本游戏文件"""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    PATCHES_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    size: _builtins.int
    md5: _builtins.str
    @_builtins.property
    def patches(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonPatchInfo]:
        """不同版本的补丁文件，如果为空则表示不需要更新"""

    def __init__(
        self,
        *,
        file: _builtins.str = ...,
        size: _builtins.int = ...,
        md5: _builtins.str = ...,
        patches: _abc.Iterable[Global___SophonPatchInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file", b"file", "md5", b"md5", "patches", b"patches", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchFile: _TypeAlias = SophonPatchFile  # noqa: Y015

@_typing.final
class SophonPatchInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    PATCH_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """更新前游戏版本"""
    @_builtins.property
    def patch(self) -> Global___SophonPatch: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        patch: Global___SophonPatch | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["patch", b"patch"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["patch", b"patch", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchInfo: _TypeAlias = SophonPatchInfo  # noqa: Y015

@_typing.final
class SophonPatch(_message.Message):
    """Patch 更新模式，游戏文件补丁，注意：每个补丁都很小，一个文件中可能有多个补丁"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    BUILD_ID_FIELD_NUMBER: _builtins.int
    PATCH_FILE_SIZE_FIELD_NUMBER: _builtins.int
    PATCH_FILE_MD5_FIELD_NUMBER: _builtins.int
    PATCH_OFFSET_FIELD_NUMBER: _builtins.int
    PATCH_LENGTH_FIELD_NUMBER: _builtins.int
    ORIGINAL_FILE_NAME_FIELD_NUMBER: _builtins.int
    ORIGINAL_FILE_SIZE_FIELD_NUMBER: _builtins.int
    ORIGINAL_FILE_MD5_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    tag: _builtins.str
    build_id: _builtins.str
    patch_file_size: _builtins.int
    """文件大小"""
    patch_file_md5: _builtins.str
    patch_offset: _builtins.int
    """当前游戏文件补丁的偏移量"""
    patch_length: _builtins.int
    """当前游戏文件补丁的长度"""
    original_file_name: _builtins.str
    """如果有这个值，表示需要使用 hdiffpatch 更新，没有表示这是新文件，对应的补丁就是原文件，直接复制即可"""
    original_file_size: _builtins.int
    original_file_md5: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        tag: _builtins.str = ...,
        build_id: _builtins.str = ...,
        patch_file_size: _builtins.int = ...,
        patch_file_md5: _builtins.str = ...,
        patch_offset: _builtins.int = ...,
        patch_length: _builtins.int = ...,
        original_file_name: _builtins.str = ...,
        original_file_size: _builtins.int = ...,
        original_file_md5: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["build_id", b"build_id", "id", b"id", "original_file_md5", b"original_file_md5", "original_file_name", b"original_file_name", "original_file_size", b"original_file_size", "patch_file_md5", b"patch_file_md5", "patch_file_size", b"patch_file_size", "patch_length", b"patch_length", "patch_offset", b"patch_offset", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatch: _TypeAlias = SophonPatch  # noqa: Y015

@_typing.final
class SophonPatchDeleteTag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    DELETE_COLLECTION_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """更新前游戏版本"""
    @_builtins.property
    def delete_collection(self) -> Global___SophonPatchDeleteFileCollection: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        delete_collection: Global___SophonPatchDeleteFileCollection | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delete_collection", b"delete_collection"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delete_collection", b"delete_collection", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchDeleteTag: _TypeAlias = SophonPatchDeleteTag  # noqa: Y015

@_typing.final
class SophonPatchDeleteFileCollection(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETE_FILES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def delete_files(self) -> _containers.RepeatedCompositeFieldContainer[Global___SophonPatchDeleteFile]: ...
    def __init__(
        self,
        *,
        delete_files: _abc.Iterable[Global___SophonPatchDeleteFile] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delete_files", b"delete_files"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchDeleteFileCollection: _TypeAlias = SophonPatchDeleteFileCollection  # noqa: Y015

@_typing.final
class SophonPatchDeleteFile(_message.Message):
    """Patch 更新模式，需要删除文件"""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    size: _builtins.int
    md5: _builtins.str
    def __init__(
        self,
        *,
        file: _builtins.str = ...,
        size: _builtins.int = ...,
        md5: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file", b"file", "md5", b"md5", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SophonPatchDeleteFile: _TypeAlias = SophonPatchDeleteFile  # noqa: Y015
